# docker-Specify the compose version
version: "3"

services:
  app:
    #Build a Dockerfile in the same directory
    build: .
    #Give the container a name(Any)
    #container_name: YTdlg2
    # https://stackoverflow.com/a/71027261
    user: ${MY_UID}:${MY_GID}
    #You can keep the container running.
    tty: true
    #Mount the files in the directory to the app directory in the container
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /etc/localtime:/etc/localtime:ro
        - ~/Downloads/:/home/node
        - ~/.Xauthority:/home/node/.Xauthority
    environment:
      - DISPLAY=${DISPLAY}
      - TZ=${TZ}
      - LANG=${LANG}
      - XMODIFIERS=${XMODIFIERS}
      - QT_IM_MODULE=${QT_IM_MODULE}
      - GTK_IM_MODULE=${GTK_IM_MODULE}
      #- XMODIFIERS="@im=fcitx"
      #- QT_IM_MODULE=fcitx5
      #- GTK_IM_MODULE=fcitx
    #Mount port 1000 on the container side to port 8080 on the host side.
    #ports:
    #  - "8080:8080"
    # https://docs.docker.com/compose/compose-file/compose-file-v3/
    privileged: true
